In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.arange(0, 10, 2)
c = np.random.rand(3, 3)

print("a:", a)
print("b:", b)
print("c:\n", c)

a: [1 2 3]
b: [0 2 4 6 8]
c:
 [[0.08365368 0.90703195 0.70988572]
 [0.99023412 0.55066234 0.58638137]
 [0.86076037 0.08339225 0.60939448]]


In [2]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array:\n", a)

reshaped = a.reshape((3, 2))
print("Reshaped to 3x2:\n", reshaped)

print("First row:", a[0])
print("Second column:", a[:, 1])
print("Sub-array:\n", a[0:2, 1:3])

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
product = np.dot(x, y)
print("Matrix Multiplication:\n", product)

print("Shape of x:", x.shape)
print("Transpose of x:\n", x.T)

random_array = np.random.randint(1, 100, (4, 4))
print("Random 4x4 array:\n", random_array)
print("Mean:", np.mean(random_array))
print("Max:", np.max(random_array))
print("Sum by row:", np.sum(random_array, axis=1))


Original array:
 [[1 2 3]
 [4 5 6]]
Reshaped to 3x2:
 [[1 2]
 [3 4]
 [5 6]]
First row: [1 2 3]
Second column: [2 5]
Sub-array:
 [[2 3]
 [5 6]]
Matrix Multiplication:
 [[19 22]
 [43 50]]
Shape of x: (2, 2)
Transpose of x:
 [[1 3]
 [2 4]]
Random 4x4 array:
 [[91 35 38 54]
 [99 61 38 59]
 [41 69 96 46]
 [92 98 25  3]]
Mean: 59.0625
Max: 99
Sum by row: [218 257 252 218]


In [3]:
import pandas as pd

# Create DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [24, 27, 22],
    'Score': [85, 90, 95]
}
df = pd.DataFrame(data)
print(df)

# Load dataset
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"
df = pd.read_csv(url)

print("First 5 rows:\n", df.head())
print("\nShape:", df.shape)
print("\nColumns:", df.columns)
print("\nSummary:\n", df.describe())

# Select one column
print(df['species'].head())

# Select multiple columns
print(df[['sepal_length', 'petal_length']].head())

# Select rows
print(df.iloc[0:5])  # first 5 rows

# Filter rows where petal_length > 1.5
filtered = df[df['petal_length'] > 1.5]
print(filtered.head())

# Average petal length for each species
grouped = df.groupby('species')['petal_length'].mean()
print(grouped)

print(df.isnull().sum())


      Name  Age  Score
0    Alice   24     85
1      Bob   27     90
2  Charlie   22     95
First 5 rows:
    sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

Shape: (150, 5)

Columns: Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

Summary:
        sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
5